### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rafinskipg** [rafinskipg/git-changelog#13]
For v1

-  avoid using Angular commit standards and allow any configuration through .changelogrc

**Comment by JohnnyEstilles** [comment]
+1 ... this would be AWESOME!

**Comment by rafinskipg** [comment]
@JohnnyEstilles I'm going to start working on this

**Comment by JohnnyEstilles** [comment]
That's great news! I'm actually working on a `gulp` version of this project. The OSS projects to which I contribute are split between `grunt` and `gulp` so I kinda need both. :-)

**Comment by rafinskipg** [comment]
Nice, it works as a CLI so you can just add a wrapper on that.

I have published a 0.1.6 version that solves some bugs, but there are some hidden bugs that i'm fixing by adding more tests, see:

https://github.com/rafinskipg/git-changelog/issues/16

Once I'm done with the tests and all the functionality works as described i'll start with the `.changelog.rc` configuration file

**Comment by rafinskipg** [comment]
I would like to remove all the deprecated params for version 0.2.0. 

@JohnnyEstilles  If you have any suggestion or improvement, let me know :)

Thank you

**Comment by JohnnyEstilles** [comment]
> Nice, it works as a CLI so you can just add a wrapper on that.

Given that `gulp` is stream oriented, I think it would better for me to recreate to the functionality than simply wrap your CLI.

> I have published a 0.1.6 version that solves some bugs, but there are some hidden bugs that i'm fixing by adding more tests, see:

I definitely agree with the need to increase the project's test coverage before you proceed with `0.2.0`.

> I would like to remove all the deprecated params for version 0.2.0.

Deprecate at will! We've had fair warning and should no longer be using them.

> If you have any suggestion or improvement, let me know :)

I opened at new issue (#19) to outline my suggestions.

**Comment by rafinskipg** [comment]
* 0.2.0 *
- Logo
- .changelogrc

**Comment by rafinskipg** [comment]
Continues in #32
