### ISSUE TITLE
Not possible to overwrite defaults

### ISSUE THREAD

**Issue by andre-ferreira-qlik** [rafinskipg/git-changelog#14]
Here's my configuration:

```
grunt.config('git_changelog', {
    minimal : {
      options: {
        app_name : grunt.file.readJSON('project-config.json').git_changelog.app_name,
        debug: true,
        file : "../CHANGELOG.md"
      }
    }
  });
```
When run:
Executing git changelog:
  - The APP name is My app - Changelog
  - The output file is CHANGELOG.md

Running "git_changelog:minimal" (git_changelog) task
Error generating changelog  [TypeError: Cannot call method 'indexOf' of undefined]
Error generating changelog  [TypeError: Cannot call method 'indexOf' of undefined]

**Comment by andre-ferreira-qlik** [comment]
The error message didn't help at all. The issue relates to the fact that no remote url was set. It would be nice to have a check on the return value of "git config --get remote.origin.url" and let the user know its not set.

**Comment by rafinskipg** [comment]
I'm gonna take a look!

**Comment by rafinskipg** [comment]
First of all, if you don't have a remote set, you can pass the option `repo_url`.

I have added a warning if you don't have `repo_url` set and it doesnt have a remote.

```
Running "git_changelog:minimal" (git_changelog) task
Error generating changelog  Sorry, you doesn't have configured any origin remote or passed a `repo_url` config value
```

You can pass the `debug` param to true if you want to see more detailed logs.

**Comment by rafinskipg** [comment]
The 2 first messages

```
The APP name is My app - Changelog
The output file is CHANGELOG.md
```

Are shown because somewhere it is requiring the `command.js` file, but this logs doesn't mean that this is being generated this way. I'm going to try to find why this is happening.

Anyway, when you set the `repo_url` and the `debug` option to true you will have this working

**Comment by rafinskipg** [comment]
I have uploaded a new version `0.1.6` that fixes that problem.

If you have any issue let me know.

Also I'm adding more tests for ensuring that the options works well.

**Comment by andre-ferreira-qlik** [comment]
Hello,
I've since move to another solution. I open the issue just to make you aware has i didn't have the time to fix and contribute. Once i have more time I'll re-check it, so thank you for fixing it.
Best regards
André

**Comment by rafinskipg** [comment]
ok @andre-ferreira-qlik , I let you know that everything is fixed, next time you can try addint the `repo_url` param: 

```
grunt.config('git_changelog', {
    minimal : {
      options: {
        app_name : grunt.file.readJSON('project-config.json').git_changelog.app_name,
        debug: true,
        repo_url: "http://repositoryurl.com/whatever",
        file : "../CHANGELOG.md"
      }
    }
  });
```
