### ISSUE TITLE
Refactor code to improve testability

### ISSUE THREAD

**Issue by JohnnyEstilles** [rafinskipg/git-changelog#19]
@rafinskipg, I completely agree with issues #16 and #18. We definitely need to increase test coverage and using`sinon` would be a great addition to the test suite.

That said, as-is the existing code-base is somewhat difficult to test. Before you proceed with `0.2.0` I suggest the following:

- [x] decouple tests from the `git_changelog` grunt task, replace with fixtures so test input is predictable
- [x] refactor code to improve testability
- [x] add a coverage tool to determine how much of test code is being tested (I suggest [istanbul][istanbul])
- [x] as suggested by #16, add tests to increase coverage
- [x] as suggested by #18, use `sinon` to stub and spy on calls to external functions

Additionally, I would:

- [x] add node `0.12.x` to travis-ci configuration
- [x] add badge to README to show the status of the current build (from travis)
- [x] add badge to README to show the test coverage of the current build (using <del>either [coveralls][coveralls] or</del> [code climate][code-climate])
- [x] improve readability
- [x] reduce method complexity

I'll be more than happy to assist with a PR.

[istanbul]: https://gotwarlost.github.io/istanbul/
[coveralls]: https://coveralls.io
[code-climate]: https://codeclimate.com

**Comment by rafinskipg** [comment]
I cannot agree more on that, Johnny. 

All what you suggest would be a great adition to git changelog. Once we are done with the refactors we can move to the changelogrc stuff. 

Feel free to pullrequest whatever you want :)

**Comment by JohnnyEstilles** [comment]
Already started working on the PR. Should submit within a day or two.

**Comment by JohnnyEstilles** [comment]
@rafinskipg, I do have a question. What is the purpose of `tasks/hacky.js`?

**Comment by rafinskipg** [comment]
It is unused, it was used prior to have the CLI option available. :)

**Comment by JohnnyEstilles** [comment]
Good. I was trying to figure out what it was, and it was driving me nuts! I will remove for cleanup purposes. 

FYI ... I'm done refactoring. I working on the adding additional tests now.

**Comment by rafinskipg** [comment]
Ty! :100:

**Comment by rafinskipg** [comment]
Hi @JohnnyEstilles The PR is merged, i have added also some changes to the writeStream that were producing weird behaviours since the beggining. The stream was not closed and sometimes the files weren't written well.

```
   stream.end();
    stream.on('finish', function() {
      deferred.resolve();
    });
```

Thank you for the nice improvements, i'm going to release version 1.7.0

**Comment by JohnnyEstilles** [comment]
Would you mind reopening this issue? There are still some pending tasks. I would prefer to close it when I'm done.

**Comment by JohnnyEstilles** [comment]
Did you run the tests before you pushed?

**Comment by rafinskipg** [comment]
Ok, yes, i saw it, now they are fixed. :+1:

**Comment by JohnnyEstilles** [comment]
Good job with the fix! :-) Almost done with this issue.

**Comment by JohnnyEstilles** [comment]
We need to work on our close climate score. 1.7! We can do better. :-)

**Comment by JohnnyEstilles** [comment]
Code climate up to 4.0, coverage at 96% ... Now we're cooking. Going to close this issue now.
