### ISSUE TITLE
ENOENT error when calling changelog.generate()

### ISSUE THREAD

**Issue by JohnnyEstilles** [rafinskipg/git-changelog#21]
Found that `.writeChangelog()` (which is called by  `.generate()` does not wait for the `open` event on its `stream` parameter. When `stream` is set to `stdout` by `.generate()` its no big deal. If the file passed to `fs.createWriteStream()` already exists it's also not an issue. However, if the file doesn't exists then writing to the stream may sporadically fail with an ENOENT error.

I propose refactoring `.writeChangelog()` into an asynchronous method (so that it can wait for the open event) that returns a promise to `.generate()`.

Will add this fix to PR #20.

**Comment by rafinskipg** [comment]
Looks good, i have never discovered this issue but felt that sometimes files weren't generating correctly sometimes, good job!

**Comment by JohnnyEstilles** [comment]
There appears to be an additional bug. `fs.createWriteStream()` fails if the destination folder doesn't exist. Probably no an issue, since most consumers likely use the default settings (i.e. `CHANGELOG.md` in the project root).

**Comment by JohnnyEstilles** [comment]
Finally fixed! :-)
