### ISSUE TITLE
Replace Q with as faster promise library (Bluebird or RSVP)

### ISSUE THREAD

**Issue by estilles** [rafinskipg/git-changelog#22]
I personally favor Bluebird, but I'm open to suggestions. :-)

**Comment by JohnnyEstilles** [comment]
Check out http://jsperf.com/pimp-vs-bluebird-vs-q-vs-rsvp/7 for a performance comparison.

**Comment by rafinskipg** [comment]
I have nothing to opose, bluebird seems cool

**Comment by glebcha** [comment]
@rafinskipg do you have cons about migration to native promises instead of using libs?
