### ISSUE TITLE
Custom logo

### ISSUE THREAD

**Issue by rafinskipg** [rafinskipg/git-changelog#24]
Generate changelogs with custom logo embebed

```
options: {
    file: 'MyChangelog.md',
    logo: './images/logo.png',
    app_name : 'Git changelog'
}
```

Adding this markup to the file

`````
<a name="">Version 0.2.0</a>

<img width="300px" src="http://upload.wikimedia.org/wikipedia/commons/4/4a/Logo_2013_Google.png" />

__Git changelog__

_a project by Google Corp_


#  v0.2.0 (2015-04-21)


## Bug Fixes
`````

That will generate a similar output to this:

![changeloglogo](https://cloud.githubusercontent.com/assets/1152768/7254469/9ae4230a-e843-11e4-950c-e22619f35a03.png)

**Comment by JohnnyEstilles** [comment]
Just out of curiosity, why use HTML (`<img>` tag) vs markdown?

**Comment by rafinskipg** [comment]
I think i decided to use the img tag because of the availability to add styles, so we can set a maximum width for the logo. I don't know if the markdown tag allows to use styles to wrap the image

**Comment by JohnnyEstilles** [comment]
Got it! :-)

**Comment by rafinskipg** [comment]
I have started working on this :)
