### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by JohnnyEstilles** [rafinskipg/git-changelog#26]
@rafinskipg, what do you think of this as our project logo?

![git-changelog-logo](https://cloud.githubusercontent.com/assets/5514878/7625073/1c4d14b8-fa25-11e4-987f-fe113ab73f87.png)

**Comment by rafinskipg** [comment]
+1

**Comment by JohnnyEstilles** [comment]
New logo added via e29b2dd8e088386eeec3f0c125973de6c8cdc2c6.
