### ISSUE TITLE
Simplify Changelog#generate by using `fs-extra` to create stream

### ISSUE THREAD

**Issue by JohnnyEstilles** [rafinskipg/git-changelog#27]
[fs-extra](https://www.npmjs.com/package/fs-extra#emptydir-dir-callback) has an `#createOutputStream` method that is exactly like `fs#createWriteStream`, but if the directory does not exist, it's created. This will allow us to simply the logic in `Changelog#generate`.

This refactoring will be a backwards compatible change.

What do you say @rafinskipg?

**Comment by rafinskipg** [comment]
i say :+1:

**Comment by JohnnyEstilles** [comment]
Implemented via #30
