### ISSUE TITLE
v0.2.0

### ISSUE THREAD

**Issue by rafinskipg** [rafinskipg/git-changelog#32]
Lists of tasks needed : 

- [ ] Group commits by tag when generating from the beggining of time
- [ ] Add a breaking changes section to our readme when the 0.2.0 is released
- [ ] Add our own changelog once we generate next versions
- [ ] Create our own .changelogrc file for our project
- [X] Change log colors
- [X] Clean readme
- [X] Logo in changelogs

**Comment by rafinskipg** [comment]
Updated README https://github.com/rafinskipg/git-changelog/blob/changelogrc/README.md

**Comment by JohnnyEstilles** [comment]
README looks much better. :-) :+1:

**Comment by daddykotex** [comment]
Hey @rafinskipg 

Thanks for the tool it is great. I'm thinking of adding it to our build process. Unfortunately, we use JIRA and I didn't find a way to generate proper URL to the ticket. I would like to fork and add the feature. What do you think? Is it something that could find it's way in the main repo? I'm asking so I don't work too much for something that will never be used by the rest of the `git-changelog` community.

Thank you

**Comment by rafinskipg** [comment]
Yeah @daddykotex  It would be great to have that feature, as the most used are github or Bitbucket + Jira

I'm closing this issue because version 1.0.0 has been released despite the fact that not all the features are implemented
