### ISSUE TITLE
Getting "Error generating changelog  undefined" error when I try to re-generate changelog

### ISSUE THREAD

**Issue by stojanovic** [rafinskipg/git-changelog#35]
Here's everything, I tried with `--debug` but it's not returning any better error:

```
slobodan:webapp 🚀  git-changelog -a "OMG! I Can Meditate." -d
Executing git changelog:
Debug enabled
  - The APP name is OMG! I Can Meditate.
  - The output file is CHANGELOG.md
Error generating changelog  undefined
```

**Comment by rafinskipg** [comment]
Hi @stojanovic  can you do a "git log" command and send me the logs to see what can be the problem?

Also try doing `git changelog -e` and tell me what happens.

Ty

**Comment by stojanovic** [comment]
```
slobodan:webapp 🚀  git changelog -e
Executing git changelog:
  - Extended, getting log since the BigBang
  - The APP name is My app - Changelog
  - The output file is CHANGELOG.md
Finished generating log Yai!
```

But `git-changelog` still fails :)

**Comment by richardthombs** [comment]
Do you have any tags defined? If not, I think you might have to include `-t false` in order to get it to work.

**Comment by stojanovic** [comment]
I had tags at that point and I tried with `-t false` and it wasn't working.
In the meantime I switched to a new laptop and upgraded OS X so now it works, not sure if it was version or some other issue, but I tried to reinstall it, of course.
Closing this since I don't have an issue anymore.
