### ISSUE TITLE
pull-requests and merge commits

### ISSUE THREAD

**Issue by chrisjbrown** [rafinskipg/git-changelog#36]
How are people dealing with the automatically generated commit messages? I get 'warning incorrect commit messages' for these.

ex:

'Merge pull request #5 from ...'

'Merge branch 'feature A'

**Comment by richardthombs** [comment]
Speaking for myself, I make sure that all branches have been rebased to to head of master before merging so that you always get fast-forward merges.

**Comment by rafinskipg** [comment]
Maybe we can try to add a way to parse this automattic generated messages into a list of pull requests and branch merged

**Comment by chrisjbrown** [comment]
Makes sense to me. I'm surprised others haven't had the same issue.

**Comment by rafinskipg** [comment]
Hi @chrisjbrown  In version v1.0.0 (despite it's not very well implemented :shaved_ice: ) you can add some greps for pull requests and branch merges, using this configuration:
```
{
              "title": "Branchs merged",
              "grep": "^Merge branch"
            },
            {
              "title" : "Pull requests merged",
              "grep": "^Merge pull request"
            }
```
under the `sections` zone
