### ISSUE TITLE
Incorrect url being generated for the commit id (HELP WANTED)

### ISSUE THREAD

**Issue by angelblade27** [rafinskipg/git-changelog#40]
I have my config as such  ( removing some internal stuff)

```
    git_changelog: {
            release_notes: {
                options: {
                    file: 'RELEASE_NOTES.md',
                    app_name: 'TEST',
                    repo_url: 'https://<internal git lab host>/<group>/<test>',
                    grep_commits: '^fix|^feat|^docs|^refactor|^chore|^style|^test|BREAKING'
                }
            }
        }
```

and when I generate the change log the link to the commit gets formatted as such
https://<internal git lab host>/<group>/<test>/commits/426fc8efaea3b245f7ca07532e9edee644f3fe42

For some reason it has 'commits' instead of 'commit' which messes up the link

**Comment by StanDimitroff** [comment]
Same here. Issues also are referenced with wrong links. Is there an issue with the GitLab hosts?

`{
    "app_name": “Test”,
    "branch" : “master”,
    "repo_url": "https://<internal git lab host>/<group>/<test>",
    "version" : "v1.0.0",
    "file": "CHANGELOG.md",
    "sections": [
        {
            "title": "Bug Fixes",
            "grep": "^fix"
        },
        {
            "title": "Features",
            "grep": "^feat"
        },
        {
            "title": "Documentation",
            "grep": "^docs"
        },
        {
            "title": "Breaking changes",
            "grep": "BREAKING"
        },
        {
            "title": "Refactor",
            "grep": "^refactor"
        },
        {
            "title": "Style",
            "grep": "^style"
        },
        {
            "title": "Test",
            "grep": "^test"
        },
        {
            "title": "Chore",
            "grep": "^chore"
        },
        {
            "title": "Branchs merged",
            "grep": "^Merge branch"
        },
        {
            "title" : "Pull requests merged",
            "grep": "^Merge pull request"
        }
    ]
}`

**Comment by rafinskipg** [comment]
Yep @StanDimitroff @angelblade27 

Currently it only uses github and bitbucket provider links. You can expand this code in order to get the correct link formats:

```
'use strict';

var debug = require('debug')('changelog:getProviderLinks');

function getProviderLinks() {
  debug('getting provider links');
  // This is just in case they differ their urls at some point in the future.
  // Also brings the posibility of adding more providers
  var providerLinks = {
    github: {
      issue: '[#%s](' + this.options.repo_url + '/issues/%s)',
      commit: '[%s](' + this.options.repo_url + '/commit/%s)'
    },
    bitbucket: {
      issue: '[#%s](' + this.options.repo_url + '/issues/%s)',
      commit: '[%s](' + this.options.repo_url + '/commits/%s)'
    }
  };

  this.provider = this.options.repo_url.indexOf('github.com') !== -1 ? 'github' :'bitbucket';
  this.links = providerLinks[this.provider];
}

module.exports = getProviderLinks;

```

It is under `tasks/lib/get-provider-links.js`. All the help is welcome!
