### ISSUE TITLE
Remove Grunt from peerDependencies

### ISSUE THREAD

**Issue by mlarcher** [rafinskipg/git-changelog#48]
Considering that the module works like a charm without grunt, would you mind removing grunt from the peerDependencies in the package.json ? It prevents using shrinkwrap as we don't use grunt at all. What do you think ?

**Comment by rafinskipg** [comment]
I'll do it yes! I also have to end that refactor i started xD

Spam me if i forgot to do it

**Comment by mlarcher** [comment]
Any chance you make a suick patch version for that before finishing the refacto ?

**Comment by rafinskipg** [comment]
@mlarcher  Done in version 1.0.0 ,

**Comment by mlarcher** [comment]
Great, thank you!
