### ISSUE TITLE
Header image is hardcoded to 300px

### ISSUE THREAD

**Issue by mlarcher** [rafinskipg/git-changelog#53]
https://github.com/rafinskipg/git-changelog/blob/master/tasks/lib/print-header.js#L7
Why not let the image native width apply ?

**Comment by rafinskipg** [comment]
+1 :dancer:

**Comment by rafinskipg** [comment]
maybe we could make it configurable through some styles and templating.

**Comment by rafinskipg** [comment]
I have added templates to the new version @mlarcher , so closing, i will release it as soon as i can
