### ISSUE TITLE
Use consistent case on commit scopes

### ISSUE THREAD

**Issue by simonrenoult** [rafinskipg/git-changelog#54]
I find a bit silly to end up with several `scopes` (eg: https://github.com/rafinskipg/git-changelog/blob/master/EXTENDEDCHANGELOG.md `README` vs `readme`) simply because the scope has been written with different cases. Couldn't it be uppercased/lowercased (or maybe have an option to enable that?)

**Comment by rafinskipg** [comment]
yay, it makes sense. 

Also the "grep" option maybe can do the trick for now, 

`git log --grep="%s" -E --format=%s %s..' + (this.options.branch ? `

If you can send a grep that accepts both uppercase and lower case, it will work. 

Can you try that? @simonrenoult

**Comment by alampros** [comment]
You can use the `-i` flag for `git log` (see [man](https://www.kernel.org/pub/software/scm/git/docs/git-log.html))

**Comment by rafinskipg** [comment]
@alampros thanks!

@simonrenoult  its done! i'll release a patch

**Comment by rafinskipg** [comment]
But I see that it did not work as expected. I should take more time  :dancer:
