### ISSUE TITLE
Show warnings by default

### ISSUE THREAD

**Issue by Sjors** [rafinskipg/git-changelog#56]
E.g. `Invalid changelogrc file` is pretty crucial; I didn't realise this was the issue until I ran with `--debug`.

Alternatively some warnings could be upgraded to errors.

**Comment by rafinskipg** [comment]
Ok @Sjors  Any suggestion is welcomed! (Any PR too xD ) I will try to look at this as soon as i can.

**Comment by rafinskipg** [comment]
Hello @Sjors I have fixed it in the "templating" branch, i will merge once i resolve all the important issues. Also now it will support template configuration for printing the changelog. (With underscore templates.. ugh... haha)
