### ISSUE TITLE
How to run the `git-changelog` locally without install globally?

### ISSUE THREAD

**Issue by adamchenwei** [rafinskipg/git-changelog#69]
I tried to run it with `./node_modules/git-changelog git-changelog` seems not really working. Is there a right way to do it if I do not want to install it globally?

**Comment by adamchenwei** [comment]
Found it!! `./node_modules/git-changelog/tasks/command.js`

**Comment by brettpostin** [comment]
A safer option may be `./node_modules/.bin/git-changelog`
