### ISSUE TITLE
Multiple Sections in single commit

### ISSUE THREAD

**Issue by wahmedswl** [rafinskipg/git-changelog#71]
Hi,
   I have following commit message

```
BREAKING: String.As has been changed to BaseUrl to better describe it feature: T.String for Encode and Typed for Decode
```

It isn't added to changelog, is there something missing or i am doing wrong? Is there something there for multiple sections data in single commit just like this one?

Thanks

**Comment by richardthombs** [comment]
As a point of style, I would have made those changes as two separate commits, and I expect that's what the tool expects.

**Comment by rafinskipg** [comment]
You can now customize the commits as seen in https://github.com/rafinskipg/git-changelog/pull/91 , in the template you can add also some kind of extra parsing
