### ISSUE TITLE
Date of commit

### ISSUE THREAD

**Issue by youvalteboul** [rafinskipg/git-changelog#79]
Hi,
i want to add the date of the commit in changelog.

it is possible to set a custom format of git log and get the commit date ?

thank you

**Comment by rafinskipg** [comment]
I will introduce a commit template so you can use it @youvalteboul

**Comment by rafinskipg** [comment]
@youvalteboul  https://github.com/rafinskipg/git-changelog/pull/91 will fix this, you can customize the commit template afterwards
