### ISSUE TITLE
template docs

### ISSUE THREAD

**Issue by addicted2sounds** [rafinskipg/git-changelog#83]
Are there any docs on creating custom template? How can I find out `commit`/`section` object components. I want to add commit message body to the log. How can I achieve that?

**Comment by rafinskipg** [comment]
@addicted2sounds  I will introduce a commit template so you can customize it

**Comment by rafinskipg** [comment]
@addicted2sounds we introduced a commit template, check the docs and examples to see how to add it

```
<%= commit.subject %> <%= link %> 
  <% if (closes) { %>(<%= closes %>)<% } %>
  <%= JSON.stringify(commit) %>
```
