### ISSUE TITLE
error: Bad link to repo

### ISSUE THREAD

**Issue by rafinskipg** [rafinskipg/git-changelog#93]
@glebcha  I noticed that in the master branch there is an error, now it picks the git@.. repo url instead of the https, can yout take a look at it? 

![image](https://user-images.githubusercontent.com/1152768/75894774-02b64a00-5e35-11ea-965e-2148fe49c97a.png)

**Comment by glebcha** [comment]
The solution is to parse url taken with `git config --get remote.origin.url`, get provider if it is in known list and replace common variations with https.

**Comment by glebcha** [comment]
@rafinskipg Should be fixed with https://github.com/rafinskipg/git-changelog/pull/95
